esphome:
  name: test-all

external_components:
  - source:
      type: local
      path: ../components

esp32:
  board: esp32dev
  framework:
    type: arduino

remote_transmitter:
  id: ir_led
  pin: 4
  carrier_duty_percent: 50%

climate:
  - platform: electra
    id: my_electra
    name: 'Electra'

  - platform: fujitsu
    id: my_fujitsu
    model: ARREB1E
    name: 'Fujitsu'

  - platform: panasonic
    id: my_panasonic
    model: DKE
    name: 'Panasonic'

  - platform: sharp
    id: my_sharp
    model: A705
    name: 'Sharp'

  - platform: mitsubishi
    id: my_mitsubishi_general
    model: GENERAL
    name: 'Mitsubishi General'

  - platform: mitsubishi
    id: my_mitsubishi_msy
    model: MSY
    name: 'Mitsubishi MSY'

  - platform: mitsubishi
    id: my_mitsubishi_msh
    model: MSH
    name: 'Mitsubishi MSH'

button:
  - platform: template
    name: 'Step vertical'
    on_press:
      then:
        - lambda: |-
            id(my_fujitsu).step_vertical();
